README.md, index.js, package.json, test/index.test.js
- Update to @opentelemetry/api v0.13.0.
- Replace CanonicalCode with StatusCode (no more grpc status codes).
- Replace default for extract's getter param (new API for getters).
- Replace default for inject's setter param (new API for setters).
- Confirm example app traces requests without error.
=> feat: Update to @opentelemetry/api v0.13.0.

README.md, index.js, package.json, test/index.test.js
Update `@opentelemetry/api` to version 0.14.0:
- Changed usage of `propagation.inject` and  `propagation.extract` to match the new api (See 2nd breaking change in [OpenTelemetry CHANGELOG.md](https://github.com/open-telemetry/opentelemetry-js/blob/master/CHANGELOG.md#0140))
- Run the example app: `npm run dev`
- Ping the app: `curl -i 'http://localhost:3000/'`
- Confirm the app completes the request and logs a span.
=> feat: Update to @opentelemetry/api v0.14.0.

README.md, example/index.js, index.js, test/fixtures/openTelemetryApi.js, test/index.test.js
- Add `wrapRoutes` option.
- Add `ignoreRoutes` option.
- Change plugin and hooks to async.
- Remove support for Fastify v2. (Breaking - if not using Fastify v3)
- Run the example -> `npm run dev`
- Navigate to http://localhost:3000
- Check your terminal logs - the `reply.doingWork` span's `parentId` should be the `id` of the `basic-example - GET - /` span.
=> feat: wrapRoutes and ignoreRoutes plugin options.

README.md, example/index.js, index.js, package.json, test/index.test.js
- Update to `@opentelemetry/api` v0.15.0. (See [CHANGELOG](https://github.com/open-telemetry/opentelemetry-js/blob/main/CHANGELOG.md#0150))
- The following `@opentelemetry/api` exports consumed by this plugin have been renamed:
- `setActiveSpan` -> `setSpan`
- `getActiveSpan` -> `getSpan`
- Update OpenTelemetry dev dependencies to v0.15.0.
- Run the example App.
- Go to http://localhost:3000
- Check terminal and confirm traces.
=> feat: Update to @opentelemetry/api v0.15.0.

README.md, index.js, package.json, test/fixtures/openTelemetryApi.js, test/index.test.js
- Update to `@opentelemetry/api` v0.17.0. (See [CHANGELOG](https://github.com/open-telemetry/opentelemetry-js/blob/main/CHANGELOG.md#0170))
- The following `@opentelemetry/api` exports consumed by this plugin have been renamed:
- `StatusCode` -> `SpanStatusCode`
- Update OpenTelemetry dev dependencies to v0.17.0.
- Update testing fixtures -> `NOOP_SPAN` is no longer exported from `@opentelemetry/api`.
- Run the example App.
- Go to http://localhost:3000
- Check terminal and confirm traces.
=> feat: Update to @opentelemetry/api v0.17.0.

README.md, package.json, test/index.test.js
- Update to `@opentelemetry/api` v0.18.0. (See [CHANGELOG](https://github.com/open-telemetry/opentelemetry-js/blob/main/CHANGELOG.md#0180))
- Run the example App.
- Go to http://localhost:3000
- Check terminal and confirm traces.
=> feat: Update to @opentelemetry/api v0.18.1.

package.json
Potential solution for resolving the situation where multiple "opentelemetry-api" modules are loaded.
Move all "runtime" dependencies to "devDependencies".
Alternative would be to use peer dependencies, as discussed on #22
=> fix: remove public dependencies due to potential conflicts in opentelemetry-api

index.js, test/index.test.js
If running within another instrumentation library, such as instrumentation-https, and the b3 headers are provided, the fastify-opentelemetry span is created under the wrong parent, this change will check to see if an existing span for a given context at creation time, and if so will use that instead of regenerating.
Note, this PR is primarily used to indicate the actual fix to #25 , but I can't figure out yet how to actually test it (so guidance would be appreciated)!
=> fix: handle when running within a nested span

README.md, package.json
Required upgrade in order to remain compatible with the latest opentelemetry releases.
Update to 1.0.0-rc.0 of the API and 0.19 of the other libraries.
Also switched the API dependency to be a peerDependency to remain consistent with the changes done in the opentelemtry APIs under https://github.com/open-telemetry/opentelemetry-js/pull/2074
=> feat: Update to @opentelemetry/api v1.0.0-rc.0

README.md, example/opentelemetry.js, index.js, package.json, test/index.test.js
Updating to latest opentelemetry versions, note the change back from an "rc" version to a dot version (see https://github.com/open-telemetry/opentelemetry-js-api/issues/74 for the history).  Hopefully the API will go 1.X final in a few weeks.
API changes including "span.context" renamed to "span.spanContext" (which does not impact this library), and the getSpan/setSpan moved to the trace object, which does impact this library.
I've added a version compatibility note to the README, but please check correct version reference when creating a release.
=> feat: update to opentelemetry/api v0.20.0

README.md, package.json, test/fixtures/openTelemetryApi.js
Update to the 1.0.0 opentelemetry-api release.
Note, as per the [upgrade-guidelines](https://github.com/open-telemetry/opentelemetry-js-api#upgrade-guidelines), NOOP_* are no longer exported, but as we were just stubbing out the functions I have simply replaced with equivalents using the direct APIs.  
The alternative here (bit more work) would be to switch around the test setup and utilise the [InMemorySpanExporter](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-tracing/src/export/InMemorySpanExporter.ts) to verify spans exported at the end instead (but slightly beyond scope of this change).
=> feat: update to opentelemetry-api 1.0.0

README.md, fastify-opentelemetry.d.ts, index.js, test/index.test.js, test/types/fastify-opentelemetry.test-d.ts
- Updates the `ignoreRoutes` option to accept an array or a function (previously only accepted an array)
- An `ignoreRoutes` function is passed a route's path and method, and expected to return a boolean 
- Resolves #38
=> feat: Allow ignoreRoutes to be a function.

README.md, example/index.js, fastify-opentelemetry.d.ts, index.js, test/index.test.js, test/types/fastify-opentelemetry.test-d.ts
* Use low-cardinality span name. Use `routerPath` instead of raw URL
* removed service name from the option because span name does not need to contain service name, service name should be set either on the provider or exporter.
```
import { ResourceAttributes } from "@opentelemetry/semantic-conventions";
import { SimpleSpanProcessor } from "@opentelemetry/tracing";
.....
const traceProvider = new NodeTracerProvider({
resource: new Resource({
[ResourceAttributes.SERVICE_NAME]: "myservice",
}),
});
```
**BREAKING CHANGE!**: service name removed from the usage and formatSpanName
Closes #40
=> fix!: use low-cardinality span name and remove serviceName option

README.md
The sample for openTelemetryConfig.js is missing a `,`.
=> fix example of openTelemetryConfig.js in README.md 

.github/workflows/release.yml, .github/workflows/validate.yml, index.js, package.json, test/index.test.js
Hello!
Fastify just released their version 4, so here's the update in this package.
I also upgraded `engines.node` to v14 (in Github Actions as well) as I think fastify started to use [Optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), introduced in node 14.
3 tests are failing with wrapRoutes, so I'm investigating them at the moment
=> chore(fastify): upgrade fastify to 4.x

README.md
**tl/dr**: Since fastify v4, `fastify.register` must be awaited when registering the `onRoute` hook, which is necessary when using `wrapRoutes: true`
________
We have a fastify-based web service which uses opentelemetry for tracing (custom traces, db, etc.). To instrument fastify, we use `fastify-opentelemetry`, which so far worked perfectly.
Since upgrading to fastify v4, we have noticed that the resulting spans from a single request are not connected anymore. Usually, with `{ wrapRoutes: true }`, we would see a trace like this: `fastify (GET route/) => manually created span => some DB call`. Now, the fastify spans are transmitted on their own, as are the other spans (though in the example above there would still be the connected trace `manually created span => some DB call`); the spans …
=> docs: Update readme to await fastify register call

.github/workflows/validate.yaml, package.json, test/index.test.js
- For some reason test coverage started dipping under 100%, but only on Node v14 and not v16
- Currently: https://github.com/autotelic/fastify-opentelemetry/runs/7963898090?check_suite_focus=true#step:5:31
- Previously: https://github.com/autotelic/fastify-opentelemetry/runs/6891777049?check_suite_focus=true#step:5:30
- No changes on our part aside from docs update
- Was able to reproduce locally, but only on Node v14
- Looks like we missed adding an `await` to the `fastify.register` call in our `setupTests` function
- Updating this fixed the issue 
- Not sure why this didn't cause an issue when we first updated to Fastify v4 (#46 )
- Updated validate workflow to run tests on Node v14 as well as v16
- Updated `tap` to latest version
- Confirm validate workflow passes
=> test: Fix missing line coverage when using Node v14

package.json
This package currently relies on `fastify-plugin@^3.0.`0 which isn't supported by fastify 4:
> `FastifyError: fastify-plugin: fastify-opentelemetry - expected '3.x' fastify version, '4.9.2' is installed`
upgrading to `fastify-plugin@^4.0.0` should fix this
=> Fix fastify v4 support by upgrading to fastify-plugin@^4.0.0

index.js, test/index.test.js
`request.routerPath` was deprecated in fastify@4.23.0. Since then it produces the following warning:
```
[FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`
```
`request.routeOptions` was added in fastify@4.10.0. This approach supports backward compatibility while also avoiding accessing `request.routerPath` in case of a 404 in versions prior to 4.10.0.
Prior to this change, the test suite emitted this warning 11 times. It is now emitted once, only for the new test which covers the case in which `request.routeOptions` does not exist.
See also open-telemetry/opentelemetry-js-contrib#1757
=> fix: use request.routeOptions instead of deprecated request.routerPath

fastify-opentelemetry.d.ts
Changing the `.d.ts` file default export syntax to be more compatible.
https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#default-exports
> Note that using export default in your .d.ts files requires esModuleInterop: true to work. If you can’t have esModuleInterop: true in your project, such as when you’re submitting a PR to Definitely Typed, you’ll have to use the export= syntax instead. This older syntax is harder to use but works everywhere. Here’s how the above example would have to be written using export=:
=> Use more compatible default export ts syntax

index.js, test/index.test.js
I encountered [this issue](https://github.com/fastify/fastify-static/issues/434) when using along side `@fastify/static`
=> fix: wrapped route handlers were forced to be async or return a promise

README.md
Noticed that this template string was missing a `$` character, so it won't interpolate this variable. This fixes the readme.
=> Fix minor mistake in README

index.js, test/index.test.js
This approach will capture all hooks called on a request when wrapping routes rather than just the route handler itself.
I think this might not match the intention of your API design though. If that's the case, perhaps this could be a new option.
Right now, in my application I'm doing this instead of using `wrapRoutes`
```js
fastify.register(openTelemetryPlugin);
fastify.addHook('onRequest', (request, reply, done) => {
const { context } = request.openTelemetry();
openTelemetry.context.with(context, done);
});
```
=> feat: include hooks not within route handler when wrapping routes

README.md, fastify-opentelemetry.d.ts, index.js, test/fixtures/openTelemetryApi.js, test/index.test.js, test/types/fastify-opentelemetry.test-d.ts
=> feat: added new option propagateToReply

.github/workflows/release.yaml, .github/workflows/validate.yaml, example/index.js, fastify-opentelemetry.d.ts, index.js, package.json, test/index.test.js, test/types/fastify-opentelemetry.test-d.ts
- Closes #71 
- Updated the Fastify version range passed into `fastify-plugin` to `4.10.x - 5.x`
- Removed `request.routerPath` fallback usage
- `request.routeOptions` was added in Fastify v4.10.0 - hence the new minimum Fastify version for this plugin
- Bumped `fastify-plugin` to v5 
- Updated example app
* minimum fastify version of 4.10.0 is now required
=> feat: fastify v5 support

README.md, fastify-opentelemetry.d.ts, index.js, test/index.test.js, test/types/fastify-opentelemetry.test-d.ts
- Closes #69 
- Add `spanOptions` to plugin opts
- Can be a [SpanOptions](https://github.com/open-telemetry/opentelemetry-js/blob/main/api/src/trace/SpanOptions.ts) object or a function that returns a [SpanOptions](https://github.com/open-telemetry/opentelemetry-js/blob/main/api/src/trace/SpanOptions.ts) object
- The default `spanOptions` has been set to `{ kind: SpanKind.SERVER }`
=> feat: configurable spanOptions

.eslintrc, fastify-opentelemetry.d.ts, package.json
- Resolves  #74 
- View debug repo -> https://github.com/HW13/fastify-otel-ts-debug
- Build was failing after switching to `"type": "module"` -> https://github.com/HW13/fastify-otel-ts-debug/commit/14dfc00bb9f4bf3a5a4f437d80feaa26c355a886
- Build passes after [yalc](https://github.com/wclr/yalc) adding this branch -> https://github.com/HW13/fastify-otel-ts-debug/commit/3d1c26c240c31529e3f9dfc24f4850970efcc2ff
=> fix: type defs esm compatibility
